/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    categories: Category;
    articles: Article;
    downloads: Download;
    tutorials: Tutorial;
    media: Media;
    portfolios: Portfolio;
    'smart-collections': SmartCollection;
    sessions: Session;
    'upload-batches': UploadBatch;
    waitlist: Waitlist;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'portfolios';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    tutorials: TutorialsSelect<false> | TutorialsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    'smart-collections': SmartCollectionsSelect<false> | SmartCollectionsSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    'upload-batches': UploadBatchesSelect<false> | UploadBatchesSelect<true>;
    waitlist: WaitlistSelect<false> | WaitlistSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    pricing: Pricing;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  roles?: ('admin' | 'creative' | 'viewer')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: number | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
    | PricingBlock
    | SprocketDividerBlock
    | About3Block
    | ArticleGridBlock
    | DownloadGridBlock
    | TutorialGridBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  /**
   * If checked, this page is a system-critical record and cannot be deleted.
   */
  isProtected?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  title: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Canonical storage path (tenants/{userId}/{domain}/{year}/{month}/{assetId}/...).
   */
  storagePath?: string | null;
  originalUrl?: string | null;
  proxyUrl?: string | null;
  thumbnailUrl?: string | null;
  /**
   * Permanent archival catalog code (e.g. FRH-2024-0001).
   */
  accessionId?: string | null;
  /**
   * Atomic intake counter (1, 2, 3...) for scalable provenance.
   */
  archivalSequence?: number | null;
  /**
   * Archival Shoot Identity (e.g. Wildlife Expedition 2024).
   */
  shootName?: string | null;
  uploadBatchId?: (number | null) | UploadBatch;
  /**
   * Creative session this asset belongs to.
   */
  session?: (number | null) | Session;
  mediaType: 'image' | 'raw' | 'video' | 'audio' | 'document' | 'unclassified';
  ingestionStatus?: ('active' | 'processing' | 'stale' | 'ready' | 'failed') | null;
  processingStep?:
    | ('upload_complete' | 'exif_parsing' | 'generating_webp' | 'registering_assets' | 'ready' | 'failed')
    | null;
  /**
   * Primary sort key. Extracted from EXIF or file date.
   */
  captureDate?: string | null;
  technical?: {
    /**
     * Camera manufacturer (e.g. Sony, Canon, Nikon).
     */
    cameraMake?: string | null;
    /**
     * Camera model name (e.g. A7 IV, EOS R5).
     */
    cameraModel?: string | null;
    lensModel?: string | null;
    iso?: number | null;
    aperture?: number | null;
    shutterSpeed?: string | null;
    focalLength?: number | null;
  };
  location?: {
    latitude?: number | null;
    longitude?: number | null;
    address?: string | null;
  };
  manualTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Rule-based tags generated during ingestion (e.g. filename parsing).
   */
  heuristicTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Computed as width / height (e.g. 16:9).
   */
  aspectRatio?: string | null;
  errorMessage?: string | null;
  processedAt?: string | null;
  owner: number | User;
  /**
   * Original filename as uploaded (pre-slugify).
   */
  originalFilename?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  /**
   * Slugified, path-safe filename used on disk + in storagePath.
   */
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Ingest grouping. One batch per user-initiated upload session; deleting a batch nullifies the FK on media (assets survive).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-batches".
 */
export interface UploadBatch {
  id: number;
  owner: number | User;
  source: 'dashboard' | 'admin' | 'seed' | 'api';
  /**
   * Free-form admin note about this ingest session.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  /**
   * Creative session name (e.g. "Golden Hour Beach Portraits").
   */
  name: string;
  /**
   * Primary shoot date.
   */
  shootDate?: string | null;
  /**
   * Optional notes about the shoot: concept, conditions, client context.
   */
  description?: string | null;
  location?: {
    address?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  /**
   * Tags pre-applied to all assets ingested under this session.
   */
  defaultTags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Hero image shown on the Sessions grid.
   */
  coverAsset?: (number | null) | Media;
  owner: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  /**
   * Choose "Mission Statement" for high-impact, centered editorial text (e.g. for About Us page).
   */
  style?: ('default' | 'mission') | null;
  backgroundColor?: ('white' | 'surface_low') | null;
  layoutStyle?: ('default' | 'asymmetric' | 'side_by_side') | null;
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        media?: (number | null) | Media;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'media' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'media';
        value: number | Media;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  style?: ('default' | 'logoWall') | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'media' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'media';
        value: number | Media;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'media';
        value: number | Media;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  backgroundColor?: ('white' | 'surface_low') | null;
  style?: ('default' | 'pillars') | null;
  media?: (number | Media)[] | null;
  items?:
    | {
        title: string;
        /**
         * Provide an editorial takeaway for this pillar.
         */
        description: string;
        media: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock".
 */
export interface PricingBlock {
  layoutType?: ('cards' | 'asymmetric') | null;
  billing?: {
    showBillingToggle?: boolean | null;
    monthlyLabel?: string | null;
    yearlyLabel?: string | null;
  };
  intro: {
    heading: string;
    subheading?: string | null;
    showStorageEthos?: boolean | null;
    storageNotice?: string | null;
  };
  currency?: ('GBP' | 'USD' | 'EUR') | null;
  tiers?:
    | {
        title: string;
        price: string;
        description?: string | null;
        features?:
          | {
              feature?: string | null;
              id?: string | null;
            }[]
          | null;
        highlight?: boolean | null;
        accent?: ('primary' | 'secondary' | 'tertiary') | null;
        cta: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SprocketDividerBlock".
 */
export interface SprocketDividerBlock {
  backgroundColor?: ('white' | 'surface_low') | null;
  speed?: ('slow' | 'medium' | 'fast') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sprocketDivider';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "About3Block".
 */
export interface About3Block {
  title: string;
  description?: string | null;
  mainImage: number | Media;
  secondaryImage: number | Media;
  breakout: {
    logo?: (number | null) | Media;
    title: string;
    description?: string | null;
    buttonText?: string | null;
    buttonUrl?: string | null;
  };
  companies?:
    | {
        logo: number | Media;
        id?: string | null;
      }[]
    | null;
  achievementsTitle?: string | null;
  achievementsDescription?: string | null;
  achievements?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  contentSections?:
    | {
        title: string;
        content: string;
        media?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'about3';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleGridBlock".
 */
export interface ArticleGridBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Select articles to feature. Leave empty to show latest published articles.
   */
  articles?: (number | Article)[] | null;
  viewAllLabel?: string | null;
  backgroundColor?: ('white' | 'surface_low') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'articleGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Short description shown in article listing cards.
   */
  excerpt?: string | null;
  category?: ('guide' | 'workflow' | 'news' | 'tips') | null;
  readTime?: number | null;
  heroImage?: (number | null) | Media;
  publishedOn?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadGridBlock".
 */
export interface DownloadGridBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Select downloads to feature.
   */
  downloads?: (number | Download)[] | null;
  backgroundColor?: ('white' | 'surface_low') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloadGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  description?: string | null;
  fileType: 'lut' | 'template' | 'preset' | 'other';
  thumbnail?: (number | null) | Media;
  /**
   * Upload the downloadable file here.
   */
  downloadFile?: (number | null) | Media;
  /**
   * Optional. Use instead of uploading a file directly.
   */
  externalUrl?: string | null;
  /**
   * When enabled, users must be signed in to download this resource.
   */
  requiresAccount?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TutorialGridBlock".
 */
export interface TutorialGridBlock {
  heading?: string | null;
  subheading?: string | null;
  /**
   * Select tutorials to feature. Leave empty to show all published tutorials.
   */
  tutorials?: (number | Tutorial)[] | null;
  backgroundColor?: ('white' | 'surface_low') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'tutorialGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials".
 */
export interface Tutorial {
  id: number;
  title: string;
  /**
   * Short summary shown on the learn page card.
   */
  description?: string | null;
  category: 'getting-started' | 'organise' | 'publish' | 'advanced';
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  duration?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  heroImage?: (number | null) | Media;
  steps?:
    | {
        stepTitle: string;
        stepContent: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        stepImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  slug: string;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  name: string;
  /**
   * Portfolio Title (Rich Text supported for custom emphasis)
   */
  title?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Portfolio Subheading (Rich Text supported)
   */
  subheading?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Automatically generated based on username and title.
   */
  slug?: string | null;
  owner: number | User;
  visibility?: ('private' | 'public' | 'shared') | null;
  password?: string | null;
  theme?: {
    fontPairing?: ('modern-sans' | 'classic-serif' | 'tech-mono') | null;
    /**
     * Hex color for the portfolio background
     */
    backgroundColor?: string | null;
    /**
     * Hex color for the text
     */
    textColor?: string | null;
    /**
     * Hex color for accents and dividers
     */
    accentColor?: string | null;
  };
  layoutBlocks: (
    | {
        /**
         * Add and reorder images for the grid.
         */
        items: {
          media?: (number | null) | Media;
          size?: ('small' | 'medium' | 'large' | 'full') | null;
          /**
           * Override alt text for this specific gallery item
           */
          alt?: string | null;
          /**
           * Caption shown in the visual layout
           */
          caption?: string | null;
          link?: string | null;
          instanceId?: string | null;
          id?: string | null;
        }[];
        spacing?: ('small' | 'medium' | 'large' | 'none') | null;
        itemsOrder?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'grid';
      }
    | {
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        alignment?: ('left' | 'center' | 'right') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'text';
      }
    | {
        media?: (number | null) | Media;
        caption?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featured';
      }
    | {
        size?: ('small' | 'medium' | 'large') | null;
        showDivider?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'spacer';
      }
  )[];
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'portfolios';
          value: number | Portfolio;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'portfolios'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smart-collections".
 */
export interface SmartCollection {
  id: number;
  name: string;
  owner: number | User;
  /**
   * The Payload query object that defines this smart view.
   */
  filterQuery:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  icon?: ('folder' | 'tag' | 'sparkles' | 'camera' | 'map') | null;
  description?: string | null;
  /**
   * Auto-generated from asset metadata. Editing strips this flag.
   */
  isSystemGenerated?: boolean | null;
  /**
   * Hide from default grid (soft hide — never touches assets).
   */
  isHidden?: boolean | null;
  /**
   * Pin ranking — lower = earlier in grid.
   */
  sortOrder?: number | null;
  generatedFrom?: ('manual' | 'ai_tags' | 'metadata' | 'tags' | 'location' | 'media_type' | 'camera' | 'date') | null;
  /**
   * Explicit cover image override. Falls back to 4-asset mosaic.
   */
  coverAsset?: (number | null) | Media;
  /**
   * Assets always included regardless of filterQuery. Cap: 500.
   */
  manualIncludes?: (number | Media)[] | null;
  /**
   * Assets always excluded regardless of filterQuery. Exclusions take priority over inclusions.
   */
  manualExcludes?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email signups for Coming Soon page. Minimal pre-launch list.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist".
 */
export interface Waitlist {
  id: number;
  email: string;
  /**
   * Optional subscriber name.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'tutorials';
        value: number | Tutorial;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'smart-collections';
        value: number | SmartCollection;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'upload-batches';
        value: number | UploadBatch;
      } | null)
    | ({
        relationTo: 'waitlist';
        value: number | Waitlist;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        sprocketDivider?: T | SprocketDividerBlockSelect<T>;
        about3?: T | About3BlockSelect<T>;
        articleGrid?: T | ArticleGridBlockSelect<T>;
        downloadGrid?: T | DownloadGridBlockSelect<T>;
        tutorialGrid?: T | TutorialGridBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  isProtected?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  style?: T;
  backgroundColor?: T;
  layoutStyle?: T;
  columns?:
    | T
    | {
        size?: T;
        media?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  style?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  style?: T;
  media?: T;
  items?:
    | T
    | {
        title?: T;
        description?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingBlock_select".
 */
export interface PricingBlockSelect<T extends boolean = true> {
  layoutType?: T;
  billing?:
    | T
    | {
        showBillingToggle?: T;
        monthlyLabel?: T;
        yearlyLabel?: T;
      };
  intro?:
    | T
    | {
        heading?: T;
        subheading?: T;
        showStorageEthos?: T;
        storageNotice?: T;
      };
  currency?: T;
  tiers?:
    | T
    | {
        title?: T;
        price?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        highlight?: T;
        accent?: T;
        cta?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SprocketDividerBlock_select".
 */
export interface SprocketDividerBlockSelect<T extends boolean = true> {
  backgroundColor?: T;
  speed?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "About3Block_select".
 */
export interface About3BlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  mainImage?: T;
  secondaryImage?: T;
  breakout?:
    | T
    | {
        logo?: T;
        title?: T;
        description?: T;
        buttonText?: T;
        buttonUrl?: T;
      };
  companies?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  achievementsTitle?: T;
  achievementsDescription?: T;
  achievements?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  contentSections?:
    | T
    | {
        title?: T;
        content?: T;
        media?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleGridBlock_select".
 */
export interface ArticleGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  articles?: T;
  viewAllLabel?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadGridBlock_select".
 */
export interface DownloadGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  downloads?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TutorialGridBlock_select".
 */
export interface TutorialGridBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  tutorials?: T;
  backgroundColor?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  category?: T;
  readTime?: T;
  heroImage?: T;
  publishedOn?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  fileType?: T;
  thumbnail?: T;
  downloadFile?: T;
  externalUrl?: T;
  requiresAccount?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials_select".
 */
export interface TutorialsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  category?: T;
  difficulty?: T;
  duration?: T;
  order?: T;
  heroImage?: T;
  steps?:
    | T
    | {
        stepTitle?: T;
        stepContent?: T;
        stepImage?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  storagePath?: T;
  originalUrl?: T;
  proxyUrl?: T;
  thumbnailUrl?: T;
  accessionId?: T;
  archivalSequence?: T;
  shootName?: T;
  uploadBatchId?: T;
  session?: T;
  mediaType?: T;
  ingestionStatus?: T;
  processingStep?: T;
  captureDate?: T;
  technical?:
    | T
    | {
        cameraMake?: T;
        cameraModel?: T;
        lensModel?: T;
        iso?: T;
        aperture?: T;
        shutterSpeed?: T;
        focalLength?: T;
      };
  location?:
    | T
    | {
        latitude?: T;
        longitude?: T;
        address?: T;
      };
  manualTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  heuristicTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  aspectRatio?: T;
  errorMessage?: T;
  processedAt?: T;
  owner?: T;
  originalFilename?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  subheading?: T;
  slug?: T;
  owner?: T;
  visibility?: T;
  password?: T;
  theme?:
    | T
    | {
        fontPairing?: T;
        backgroundColor?: T;
        textColor?: T;
        accentColor?: T;
      };
  layoutBlocks?:
    | T
    | {
        grid?:
          | T
          | {
              items?:
                | T
                | {
                    media?: T;
                    size?: T;
                    alt?: T;
                    caption?: T;
                    link?: T;
                    instanceId?: T;
                    id?: T;
                  };
              spacing?: T;
              itemsOrder?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              content?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        featured?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        spacer?:
          | T
          | {
              size?: T;
              showDivider?: T;
              id?: T;
              blockName?: T;
            };
      };
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "smart-collections_select".
 */
export interface SmartCollectionsSelect<T extends boolean = true> {
  name?: T;
  owner?: T;
  filterQuery?: T;
  icon?: T;
  description?: T;
  isSystemGenerated?: T;
  isHidden?: T;
  sortOrder?: T;
  generatedFrom?: T;
  coverAsset?: T;
  manualIncludes?: T;
  manualExcludes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  name?: T;
  shootDate?: T;
  description?: T;
  location?:
    | T
    | {
        address?: T;
        latitude?: T;
        longitude?: T;
      };
  defaultTags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverAsset?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-batches_select".
 */
export interface UploadBatchesSelect<T extends boolean = true> {
  owner?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "waitlist_select".
 */
export interface WaitlistSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        /**
         * Check to turn this link into a dropdown menu.
         */
        group?: boolean | null;
        menuTitle?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        subItems?:
          | {
              link?: {
                /**
                 * Briefly describe this link (shown in megamenu).
                 */
                description?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  plans: {
    name: string;
    /**
     * Include currency symbol (e.g., £0, £49)
     */
    priceMonthly: string;
    /**
     * Include currency symbol (e.g., £0, £41)
     */
    priceAnnual: string;
    description: string;
    ctaText: string;
    isRecommended?: boolean | null;
    summaryFeatures?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  featureCategories?:
    | {
        name: string;
        features?:
          | {
              name: string;
              description?: string | null;
              plan1Value?: string | null;
              plan2Value?: string | null;
              plan3Value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  partnerLogos?:
    | {
        logo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  enterpriseHeading?: string | null;
  enterpriseCtaLabel?: string | null;
  enterpriseDescription?: string | null;
  /**
   * Custom title for SEO. Falls back to "Pricing | Framehouse Hub".
   */
  metaTitle?: string | null;
  /**
   * Custom description for search results.
   */
  metaDescription?: string | null;
  /**
   * Social sharing image (OpenGraph).
   */
  metaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        group?: T;
        menuTitle?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        subItems?:
          | T
          | {
              link?:
                | T
                | {
                    description?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  plans?:
    | T
    | {
        name?: T;
        priceMonthly?: T;
        priceAnnual?: T;
        description?: T;
        ctaText?: T;
        isRecommended?: T;
        summaryFeatures?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        id?: T;
      };
  featureCategories?:
    | T
    | {
        name?: T;
        features?:
          | T
          | {
              name?: T;
              description?: T;
              plan1Value?: T;
              plan2Value?: T;
              plan3Value?: T;
              id?: T;
            };
        id?: T;
      };
  partnerLogos?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  enterpriseHeading?: T;
  enterpriseCtaLabel?: T;
  enterpriseDescription?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}